/*
  Catalogo dei minigiochi: la "carta d'identità" di ognuno.

  Qui ci sono SOLO i dati (nome, categoria, abilità, durata…), che servono
  a elenchi, filtri, ricerca e pacchetti senza caricare il codice del gioco.
  Il codice vero (createParams, mount…) sta in js/games/<id>.js e viene
  caricato a richiesta con loadGame(id), solo quando si gioca.

  Per aggiungere un minigioco: crea js/games/<id>.js, aggiungi una voce qui
  e il file alla lista PRECACHE in sw.js.

  Campi:
    id           identificatore (= nome del file)
    title, icon  come appare (icon = emoji di riserva)
    image        icona disegnata (assets/icons/<id>.webp); se manca si usa l'emoji
    description  una riga, per elenchi e conto alla rovescia
    howTo        spiegazione un po' più lunga
    category     UNA categoria principale (vedi CATEGORIES)
    skills       abilità coinvolte (più di una)
    theme        ambientazione / soggetto
    duration     secondi tipici di una manche
    pace         "frenetico" | "veloce" | "tranquillo"
    input        come si comanda: "tocco" | "scorri" | "tieni premuto"
    hands        "una mano" | "due mani"
    difficultyNote  cosa cambia con la difficoltà
    scoring      come si fa punteggio
    added        data di arrivo (per il badge NUOVO)
    tags         parole libere per la ricerca
*/

export const CATEGORIES = [
  { id: "riflessi", label: "Riflessi", icon: "⚡", color: "#ffca3a" },
  { id: "memoria", label: "Memoria", icon: "🧠", color: "#c77dff" },
  { id: "attenzione", label: "Attenzione", icon: "👁️", color: "#36cfc9" },
  { id: "destrezza", label: "Destrezza", icon: "🎮", color: "#8ac926" },
  { id: "calcolo", label: "Calcolo", icon: "🔢", color: "#1982c4" },
  { id: "azzardo", label: "Azzardo", icon: "🎲", color: "#ff595e" },
  { id: "parole", label: "Parole", icon: "🔤", color: "#f15bb5" },
];

export const PACES = { frenetico: "Frenetico", veloce: "Veloce", tranquillo: "Tranquillo" };

// Un minigioco è "nuovo" per questo numero di giorni dopo l'arrivo.
const NEW_DAYS = 21;

export const CATALOG = [
  {
    id: "semaforo",
    image: "assets/icons/semaforo.webp",
    title: "Semaforo",
    icon: "🚦",
    description: "Tocca appena lo schermo diventa verde. Se tocchi prima, falsa partenza!",
    howTo: "Lo schermo è rosso. In un momento imprevedibile diventa verde: tocca il più in fretta possibile. Chi tocca col rosso fa falsa partenza e finisce ultimo.",
    category: "riflessi",
    skills: ["riflessi", "autocontrollo"],
    theme: "semaforo",
    duration: 6,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = attesa più lunga e imprevedibile.",
    scoring: "Millisecondi di reazione: meno è meglio.",
    added: "2026-09-19",
    tags: ["reazione", "classico", "velocità"],
    load: () => import("./semaforo.js"),
  },
  {
    id: "memory",
    image: "assets/icons/memory.webp",
    title: "Memory",
    icon: "🃏",
    description: "Trova tutte le coppie di forme uguali. Vince chi finisce prima.",
    howTo: "Le carte sono coperte. Girane due: se sono uguali restano scoperte, altrimenti si richiudono. Trova tutte le coppie nel minor tempo.",
    category: "memoria",
    skills: ["memoria visiva", "metodo"],
    theme: "carte e forme",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più coppie (6, 8, 10).",
    scoring: "Tempo per completare: meno è meglio.",
    added: "2026-09-19",
    tags: ["coppie", "carte", "classico", "forme"],
    load: () => import("./memory.js"),
  },
  {
    id: "sequenza",
    image: "assets/icons/sequenza.webp",
    title: "Sequenza",
    icon: "🎵",
    description: "Guarda i tasti che si accendono e ripeti la sequenza. Ogni volta si allunga di uno.",
    howTo: "Quattro tasti colorati si accendono in ordine. Ripeti la sequenza toccandoli. Ogni giro aggiunge un passo: quanto lontano arrivi?",
    category: "memoria",
    skills: ["memoria", "concentrazione"],
    theme: "tasti colorati",
    duration: 50,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = sequenza più lunga e più veloce.",
    scoring: "Passi completati: più è meglio.",
    added: "2026-09-19",
    tags: ["simon", "ritmo", "colori", "classico"],
    load: () => import("./sequenza.js"),
  },
  {
    id: "numeri",
    image: "assets/icons/numeri.webp",
    title: "Numeri",
    icon: "🔢",
    description: "Tocca i numeri in ordine, dall'1 in su, il più in fretta possibile.",
    howTo: "Una griglia di numeri in disordine. Toccali in ordine crescente. Ogni tocco sbagliato costa un secondo.",
    category: "attenzione",
    skills: ["ricerca visiva", "velocità"],
    theme: "numeri",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più numeri (12, 16, 20).",
    scoring: "Tempo per finire, +1 s per errore: meno è meglio.",
    added: "2026-09-19",
    tags: ["ordine", "griglia", "velocità"],
    load: () => import("./numeri.js"),
  },
  {
    id: "bersagli",
    image: "assets/icons/bersagli.webp",
    title: "Bersagli",
    icon: "🎯",
    description: "Tocca i bersagli prima che spariscano. Hai 20 secondi.",
    howTo: "Compaiono cerchi colorati in punti a caso e spariscono in fretta. Colpiscine più che puoi.",
    category: "destrezza",
    skills: ["precisione", "velocità"],
    theme: "bersagli",
    duration: 20,
    pace: "frenetico",
    input: "tocco",
    hands: "due mani",
    difficultyNote: "Più difficile = bersagli più piccoli e più brevi.",
    scoring: "Bersagli colpiti: più è meglio.",
    added: "2026-09-19",
    tags: ["talpa", "colpisci", "velocità"],
    load: () => import("./bersagli.js"),
  },
  {
    id: "calcoli",
    image: "assets/icons/calcoli.webp",
    title: "Calcoli",
    icon: "➕",
    description: "Rispondi a più operazioni che puoi in 25 secondi. Gli errori tolgono un punto.",
    howTo: "Un'operazione e tre risposte. Tocca quella giusta e passa alla prossima. Sbagliare toglie un punto.",
    category: "calcolo",
    skills: ["calcolo mentale", "velocità"],
    theme: "matematica",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = numeri più grandi e moltiplicazioni.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-19",
    tags: ["matematica", "somme", "scuola"],
    load: () => import("./calcoli.js"),
  },
  {
    id: "colori",
    image: "assets/icons/colori.webp",
    title: "Colori",
    icon: "🎨",
    description: "Tocca il colore con cui è SCRITTA la parola, non quello che dice. 20 secondi.",
    howTo: "Appare il nome di un colore scritto con un altro colore. Devi toccare il tasto del colore dell'inchiostro, ignorando la parola. Il cervello prova a fregarti.",
    category: "attenzione",
    skills: ["attenzione", "autocontrollo"],
    theme: "parole e colori",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più inganni e tasti che cambiano posto.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["stroop", "parole", "inganno", "colori"],
    load: () => import("./colori.js"),
  },
  {
    id: "precisione",
    image: "assets/icons/precisione.webp",
    title: "Precisione",
    icon: "🏹",
    description: "Ferma il cursore al centro della zona colorata. Cinque tiri, massimo 100 punti l'uno.",
    howTo: "Un cursore scorre avanti e indietro su una barra. Tocca quando è dentro la zona verde: più vicino al centro, più punti. Cinque tiri.",
    category: "destrezza",
    skills: ["tempismo", "calma"],
    theme: "barra e cursore",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = cursore più veloce e zona più stretta.",
    scoring: "Somma dei cinque tiri (max 500): più è meglio.",
    added: "2026-09-20",
    tags: ["tempismo", "tiro", "barra"],
    load: () => import("./precisione.js"),
  },
  {
    id: "salta",
    image: "assets/icons/salta.webp",
    title: "Salta",
    icon: "🦘",
    description: "Tocca per saltare gli ostacoli. Resisti 30 secondi!",
    howTo: "Il tuo personaggio corre da solo. Tocca per saltare gli ostacoli spinati. La corsa accelera piano piano: quanti ne superi?",
    category: "destrezza",
    skills: ["tempismo", "riflessi"],
    theme: "corsa",
    duration: 30,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più veloce, ostacoli più vicini e più alti.",
    scoring: "Ostacoli superati: più è meglio.",
    added: "2026-09-20",
    tags: ["runner", "corsa", "salto", "azione", "dino"],
    load: () => import("./salta.js"),
  },
  {
    id: "intruso",
    image: "assets/icons/intruso.webp",
    title: "Intruso",
    icon: "🔍",
    description: "Un quadrato ha un colore leggermente diverso dagli altri: toccalo! 20 secondi.",
    howTo: "Una griglia di quadrati tutti uguali… tranne uno, di una sfumatura diversa. Trovalo. A ogni griglia la differenza si riduce.",
    category: "attenzione",
    skills: ["occhio", "percezione dei colori"],
    theme: "colori e griglie",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande e differenze più sottili.",
    scoring: "Intrusi trovati meno errori: più è meglio.",
    added: "2026-09-20",
    tags: ["differenze", "sfumature", "occhio", "griglia"],
    load: () => import("./intruso.js"),
  },
  {
    id: "frecce",
    image: "assets/icons/frecce.webp",
    title: "Frecce",
    icon: "🧭",
    description: "Scorri il dito dove indica la freccia. Se è rossa, vai dalla parte opposta! 20 secondi.",
    howTo: "Appare una freccia: scorri il dito nella sua direzione. Se la freccia è rossa, scorri nella direzione opposta. Veloce!",
    category: "riflessi",
    skills: ["riflessi", "logica"],
    theme: "frecce",
    duration: 20,
    pace: "frenetico",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = più frecce rosse.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["swipe", "direzioni", "inganno", "gesto"],
    load: () => import("./frecce.js"),
  },
  {
    id: "palloncini",
    image: "assets/icons/palloncini.webp",
    title: "Palloncini",
    icon: "🎈",
    description: "Tieni premuto per gonfiare, lascia prima che scoppi! Ogni palloncino regge in modo diverso.",
    howTo: "Tieni premuto: il palloncino si gonfia e i punti salgono. Lascia prima che scoppi, altrimenti zero. Ogni palloncino ha un limite nascosto diverso.",
    category: "azzardo",
    skills: ["coraggio", "autocontrollo"],
    theme: "palloncini",
    duration: 30,
    pace: "tranquillo",
    input: "tieni premuto",
    hands: "una mano",
    difficultyNote: "Più difficile = si gonfia più in fretta e scoppia prima.",
    scoring: "Somma dei cinque palloncini (max 500): più è meglio.",
    added: "2026-09-20",
    tags: ["rischio", "suspense", "festa", "premi"],
    load: () => import("./palloncini.js"),
  },
  {
    id: "dipiu",
    image: "assets/icons/dipiu.webp",
    title: "Di più",
    icon: "⚖️",
    description: "Quale riquadro ha più pallini? Tocca in fretta! 20 secondi.",
    howTo: "Due riquadri pieni di pallini. Tocca quello che ne ha di più, a colpo d'occhio. Attenzione: i pallini non hanno tutti la stessa dimensione.",
    category: "attenzione",
    skills: ["stima", "colpo d'occhio"],
    theme: "pallini",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = quantità più vicine tra loro.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["stima", "quantità", "confronto", "occhio"],
    load: () => import("./dipiu.js"),
  },
  {
    id: "tocchi",
    image: "assets/icons/tocchi.webp",
    title: "Tocchi",
    icon: "👆",
    description: "Quanti tocchi riesci a fare in 10 secondi? Tutto lo schermo è il pulsante.",
    howTo: "Dieci secondi, un solo obiettivo: toccare lo schermo più volte che puoi. Con due dita si va più veloci… a te la scelta.",
    category: "riflessi",
    skills: ["velocità", "resistenza"],
    theme: "contatore",
    duration: 10,
    pace: "frenetico",
    input: "tocco",
    hands: "due mani",
    difficultyNote: "La difficoltà non cambia nulla: conta solo la velocità.",
    scoring: "Numero di tocchi: più è meglio.",
    added: "2026-09-21",
    tags: ["tap", "velocità", "sfida", "dita"],
    load: () => import("./tocchi.js"),
  },
  {
    id: "ritmo",
    image: "assets/icons/ritmo.webp",
    title: "Ritmo",
    icon: "🥁",
    description: "Tocca a tempo con il battito: 16 colpi, più sei preciso più punti.",
    howTo: "Senti e vedi un battito regolare. Dopo quattro battiti di preparazione, tocca esattamente sul battito per sedici volte. Ogni colpo vale fino a 100 punti.",
    category: "destrezza",
    skills: ["ritmo", "tempismo"],
    theme: "musica",
    duration: 15,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = battito più veloce (90, 110, 135 BPM).",
    scoring: "Somma della precisione dei 16 colpi (max 1600).",
    added: "2026-09-21",
    tags: ["musica", "battito", "tempo", "metronomo"],
    load: () => import("./ritmo.js"),
  },
  {
    id: "torre",
    image: "assets/icons/torre.webp",
    title: "Torre",
    icon: "🏗️",
    description: "Un blocco scorre: toccalo per farlo cadere sulla torre. La parte che sporge si perde!",
    howTo: "Sopra la torre un blocco va avanti e indietro. Tocca per farlo cadere: quello che non appoggia sul blocco sotto si stacca, e il blocco dopo è più stretto. Fino a 20 blocchi.",
    category: "destrezza",
    skills: ["tempismo", "precisione"],
    theme: "costruzione",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = blocchi più veloci.",
    scoring: "Blocchi impilati (max 20). Allineamento perfetto = nessuna perdita.",
    added: "2026-09-21",
    tags: ["stack", "blocchi", "impilare", "costruire"],
    load: () => import("./torre.js"),
  },
  {
    id: "frenata",
    image: "assets/icons/frenata.webp",
    title: "Frenata",
    icon: "🚗",
    description: "L'auto accelera verso la riga: tocca per frenare e fermati il più vicino possibile.",
    howTo: "L'auto parte da sola e accelera. Tocca una volta per frenare: si fermerà un po' più avanti. Vince chi si ferma più vicino alla riga senza superarla. Cinque tentativi.",
    category: "destrezza",
    skills: ["tempismo", "stima"],
    theme: "auto",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = accelerazioni più forti e frenata più brusca.",
    scoring: "Somma dei cinque tentativi (max 500). Oltre la riga = 0.",
    added: "2026-09-21",
    tags: ["auto", "guida", "freno", "corsa"],
    load: () => import("./frenata.js"),
  },
  {
    id: "cesto",
    image: "assets/icons/cesto.webp",
    title: "Cesto",
    icon: "🧺",
    description: "Trascina il cesto e prendi la frutta che cade. 20 secondi.",
    howTo: "La frutta cade dall'alto in punti diversi. Tieni il dito sullo schermo e trascina il cesto sotto ogni frutto. Ogni frutto preso vale un punto.",
    category: "destrezza",
    skills: ["coordinazione", "velocità"],
    theme: "frutta",
    duration: 20,
    pace: "veloce",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = frutta più veloce e più fitta.",
    scoring: "Frutti presi su quelli caduti: più è meglio.",
    added: "2026-09-21",
    tags: ["cattura", "frutta", "trascina", "cadere"],
    load: () => import("./cesto.js"),
  },
  {
    id: "lampi",
    image: "assets/icons/lampi.webp",
    title: "Lampi",
    icon: "💡",
    description: "Alcuni lampi appaiono in un attimo: quanti erano? Otto giri.",
    howTo: "Sullo schermo lampeggiano dei punti luminosi, uno dopo l'altro, in fretta. Alla fine rispondi col tastierino: quanti erano? Otto giri, sempre più rapidi.",
    category: "attenzione",
    skills: ["attenzione", "conteggio"],
    theme: "luci",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più lampi e più veloci.",
    scoring: "Risposte giuste su 8.",
    added: "2026-09-21",
    tags: ["contare", "lampi", "luci", "occhio"],
    load: () => import("./lampi.js"),
  },
  {
    id: "meta",
    image: "assets/icons/meta.webp",
    title: "Metà",
    icon: "📏",
    description: "Tocca il punto esatto a metà della barra. Cinque barre.",
    howTo: "Appare una barra colorata. Tocca dove pensi sia il suo centro esatto. Più sei vicino, più punti. A difficile le barre sono anche inclinate.",
    category: "attenzione",
    skills: ["stima", "colpo d'occhio"],
    theme: "geometria",
    duration: 20,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = barre inclinate.",
    scoring: "Somma della precisione delle cinque barre (max 500).",
    added: "2026-09-21",
    tags: ["centro", "stima", "misura", "occhio"],
    load: () => import("./meta.js"),
  },
  {
    id: "cinquesecondi",
    image: "assets/icons/cinquesecondi.webp",
    title: "Cronometro cieco",
    icon: "⏱️",
    description: "Il cronometro sparisce dopo un secondo: fermalo a 5,00 s a occhi chiusi.",
    howTo: "Tocca per avviare il cronometro. Dopo un secondo i numeri spariscono. Tocca di nuovo quando pensi che sia passato esattamente il tempo richiesto. Tre tentativi.",
    category: "attenzione",
    skills: ["senso del tempo", "calma"],
    theme: "tempo",
    duration: 25,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: 5 s sempre, visibile 2 s. Difficile: bersagli diversi (3-8 s).",
    scoring: "Somma della precisione dei tre tentativi (max 300).",
    added: "2026-09-21",
    tags: ["tempo", "cronometro", "secondi", "stima"],
    load: () => import("./cinquesecondi.js"),
  },
  {
    id: "copia",
    image: "assets/icons/copia.webp",
    title: "Copia",
    icon: "🪞",
    description: "Guarda lo schema di caselle accese, poi ricopialo. Sei schemi sempre più grandi.",
    howTo: "Una griglia mostra alcune caselle accese per un attimo, poi si spegne. Tocca le caselle per ricomporre lo stesso schema e conferma. Ogni schema ha una casella in più.",
    category: "memoria",
    skills: ["memoria visiva", "attenzione"],
    theme: "griglie",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande, schemi più fitti, meno tempo per guardare.",
    scoring: "Schemi esatti su 6.",
    added: "2026-09-21",
    tags: ["schema", "memoria", "griglia", "copiare"],
    load: () => import("./copia.js"),
  },
  {
    id: "anagrammi",
    image: "assets/icons/anagrammi.webp",
    title: "Anagrammi",
    icon: "🔤",
    description: "Le lettere sono in disordine: tocca nell'ordine giusto per ricomporre la parola. 30 secondi.",
    howTo: "Vedi le lettere di una parola mescolate. Toccale nell'ordine giusto: se la parola è corretta passi alla prossima, altrimenti le lettere tornano a posto. Puoi saltare una parola.",
    category: "parole",
    skills: ["vocabolario", "logica"],
    theme: "parole",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = parole più lunghe.",
    scoring: "Parole ricomposte: più è meglio.",
    added: "2026-09-21",
    tags: ["lettere", "parole", "anagramma", "italiano"],
    load: () => import("./anagrammi.js"),
  },
  {
    id: "altobasso",
    image: "assets/icons/altobasso.webp",
    title: "Alto o basso",
    icon: "🎴",
    description: "Il prossimo numero sarà più alto o più basso? 20 secondi di scommesse.",
    howTo: "Una carta mostra un numero. Indovina se la prossima sarà più alta o più bassa. Giusto +1, sbagliato -1. Con un po' di logica (e un po' di fortuna) si fanno serie lunghe.",
    category: "azzardo",
    skills: ["probabilità", "intuito"],
    theme: "carte",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: numeri da 1 a 20. Normale e difficile: da 1 a 100.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["carte", "scommessa", "numeri", "fortuna"],
    load: () => import("./altobasso.js"),
  },
  {
    id: "dieci",
    image: "assets/icons/dieci.webp",
    title: "Dieci",
    icon: "🔟",
    description: "Tocca due numeri che sommati fanno 10. Spariscono e ne arrivano altri. 25 secondi.",
    howTo: "Una griglia di numeri. Tocca due numeri la cui somma è 10: spariscono e vengono sostituiti. C'è sempre almeno una coppia possibile. Più coppie trovi, meglio è.",
    category: "calcolo",
    skills: ["calcolo", "ricerca visiva"],
    theme: "numeri",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande.",
    scoring: "Coppie trovate: più è meglio.",
    added: "2026-09-21",
    tags: ["somma", "coppie", "matematica", "dieci"],
    load: () => import("./dieci.js"),
  },
  {
    id: "labirinto",
    image: "assets/icons/labirinto.webp",
    title: "Labirinto",
    icon: "🌀",
    description: "Trascina il dito dall'ingresso all'uscita senza toccare i muri.",
    howTo: "Appoggia il dito sulla casella verde e scorri fino alla stella dorata restando nei corridoi. Se tocchi un muro torni all'ingresso e perdi un secondo. Vince chi esce prima.",
    category: "destrezza",
    skills: ["precisione", "orientamento"],
    theme: "labirinto",
    duration: 40,
    pace: "tranquillo",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = labirinto più grande e corridoi più stretti.",
    scoring: "Tempo per uscire, +1 s per ogni tocco al muro: meno è meglio.",
    added: "2026-09-21",
    tags: ["labirinto", "dito", "percorso", "muri"],
    load: () => import("./labirinto.js"),
  },
  {
    id: "melodia",
    image: "assets/icons/melodia.webp",
    title: "Melodia",
    icon: "🎹",
    description: "Ascolta una melodia sui quattro tasti e ripetila. Ogni giro è nuova e più lunga.",
    howTo: "Quattro tasti come un pianoforte. Una melodia suona una volta sola (i tasti si accendono): ripetila toccando i tasti nello stesso ordine. Ogni giro la melodia cambia e si allunga. Se sbagli, si passa alla successiva.",
    category: "memoria",
    skills: ["memoria uditiva", "attenzione"],
    theme: "pianoforte",
    duration: 50,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = melodie più veloci.",
    scoring: "Note giuste (max 52).",
    added: "2026-09-21",
    tags: ["musica", "note", "memoria", "piano"],
    load: () => import("./melodia.js"),
  },
  {
    id: "ordina",
    image: "assets/icons/ordina.webp",
    title: "Ordina",
    icon: "🫧",
    description: "Tocca i cerchi dal più piccolo al più grande, serie dopo serie.",
    howTo: "Compaiono cerchi di grandezze diverse: toccali in ordine, dal più piccolo al più grande. Finita una serie ne arriva un'altra. Un errore fa perdere tempo, non punti.",
    category: "attenzione",
    skills: ["colpo d'occhio", "velocità"],
    theme: "bolle",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più cerchi per serie (5, 7, 9) e grandezze più vicine.",
    scoring: "Tocchi giusti in 25 s: più è meglio.",
    added: "2026-09-21",
    tags: ["grandezza", "ordine", "cerchi", "occhio"],
    load: () => import("./ordina.js"),
  },
  {
    id: "parola",
    image: "assets/icons/parola.webp",
    title: "Parola nascosta",
    icon: "🔠",
    description: "Trova la parola nascosta nella griglia di lettere e tocca le sue lettere in ordine.",
    howTo: "In alto c'è la parola da trovare; nella griglia è scritta in orizzontale o in verticale. Tocca la sua prima lettera, poi le altre in ordine. Una lettera sbagliata azzera la selezione. 40 secondi, più parole possibili.",
    category: "parole",
    skills: ["lettura", "colpo d'occhio"],
    theme: "griglia di lettere",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande (5×5, 6×6, 7×7).",
    scoring: "Parole trovate: più è meglio.",
    added: "2026-09-21",
    tags: ["parole", "lettere", "cerca", "griglia"],
    load: () => import("./parola.js"),
  },
  {
    id: "tris",
    image: "assets/icons/tris.webp",
    title: "Tris veloce",
    icon: "❌",
    description: "Partite lampo di tris contro il telefono: vinci 3 punti, pareggi 1.",
    howTo: "Sei la X e cominci tu. Vinci mettendo tre X in fila; il telefono risponde subito. Finita una partita ne parte un'altra, per 30 secondi. Vittoria 3 punti, pareggio 1, sconfitta 0.",
    category: "attenzione",
    skills: ["logica", "rapidità"],
    theme: "tris",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = avversario che si distrae di rado.",
    scoring: "Punti (3 per vittoria, 1 per pareggio): più è meglio.",
    added: "2026-09-21",
    tags: ["tris", "logica", "partite", "x e o"],
    load: () => import("./tris.js"),
  },
  {
    id: "pesca",
    image: "assets/icons/pesca.webp",
    title: "Pesca",
    icon: "🎣",
    description: "Quando il galleggiante affonda, tocca subito: cinque pesci, più sei rapido più punti.",
    howTo: "Il galleggiante ondeggia. In un momento imprevedibile un pesce abbocca e il galleggiante affonda di colpo: tocca il più in fretta possibile. Se tocchi prima, il pesce scappa. Attento ai finti morsi nei livelli più difficili.",
    category: "riflessi",
    skills: ["riflessi", "pazienza"],
    theme: "lago",
    duration: 35,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = meno tempo per rispondere e finti morsi.",
    scoring: "Somma dei cinque pesci (max 500): più è meglio.",
    added: "2026-09-21",
    tags: ["pesce", "attesa", "reazione", "acqua"],
    load: () => import("./pesca.js"),
  },
  {
    id: "traiettoria",
    image: "assets/icons/traiettoria.webp",
    title: "Traiettoria",
    icon: "🎯",
    description: "Scorri dalla palla verso il bersaglio in movimento: otto lanci, centra più che puoi.",
    howTo: "Il bersaglio si muove in alto. Scorri il dito dalla palla nella direzione in cui vuoi lanciarla: la palla parte dritta. Centro pieno 100 punti, anelli esterni meno. Otto lanci.",
    category: "destrezza",
    skills: ["mira", "tempismo"],
    theme: "tiro al bersaglio",
    duration: 35,
    pace: "veloce",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = bersaglio più veloce.",
    scoring: "Somma degli otto lanci (max 800): più è meglio.",
    added: "2026-09-21",
    tags: ["bersaglio", "lancio", "mira", "palla"],
    load: () => import("./traiettoria.js"),
  },
  {
    id: "capitali",
    image: "assets/icons/capitali.webp",
    title: "Capitali",
    icon: "🌍",
    description: "Qual è la capitale di…? Quattro risposte, 25 secondi a raffica.",
    howTo: "Compare un paese con la sua bandiera: tocca la capitale giusta tra le quattro. Ogni risposta giusta vale +1, ogni errore −1. Più rispondi, più punti.",
    category: "memoria",
    skills: ["cultura", "rapidità"],
    theme: "geografia",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: solo capitali famosissime. Difficile: anche quelle meno note.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["geografia", "quiz", "bandiere", "mondo"],
    load: () => import("./capitali.js"),
  },
];

export const ALL_GAME_IDS = CATALOG.map((g) => g.id);

export function getEntry(id) {
  return CATALOG.find((g) => g.id === id);
}

export function getCategory(id) {
  return CATEGORIES.find((c) => c.id === id);
}

export function isNew(entry, now = Date.now()) {
  const added = Date.parse(entry.added);
  return Number.isFinite(added) && now - added < NEW_DAYS * 86400000;
}

// Ricerca testuale su tutti i campi descrittivi.
export function matches(entry, query) {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const hay = [
    entry.title, entry.description, entry.howTo, entry.theme, entry.category,
    entry.pace, entry.input, ...entry.skills, ...entry.tags,
    getCategory(entry.category)?.label,
  ].join(" ").toLowerCase();
  return q.split(/\s+/).every((word) => hay.includes(word));
}

// ---------------------------------------------------------------
// Caricamento a richiesta del codice di un minigioco
// ---------------------------------------------------------------

const loaded = new Map();   // id -> Promise del gioco completo
const resolved = new Map(); // id -> gioco completo, quando il caricamento è finito

// Ritorna il gioco completo: scheda del catalogo + codice del modulo.
export async function loadGame(id) {
  if (loaded.has(id)) return loaded.get(id);
  const entry = getEntry(id);
  if (!entry) throw new Error(`Minigioco sconosciuto: ${id}`);
  const promise = entry.load().then((mod) => {
    const game = { ...entry, ...mod.default };
    resolved.set(id, game);
    return game;
  });
  loaded.set(id, promise);
  return promise;
}

// Il gioco completo se è già stato caricato, altrimenti null (senza attese).
export function getLoaded(id) {
  return resolved.get(id) || null;
}

export function preloadGames(ids) {
  return Promise.allSettled(ids.map((id) => loadGame(id)));
}
