/*
  Catalogo dei minigiochi: la "carta d'identità" di ognuno.

  Qui ci sono SOLO i dati (nome, categoria, abilità, durata…), che servono
  a elenchi, filtri, ricerca e pacchetti senza caricare il codice del gioco.
  Il codice vero (createParams, mount…) sta in js/games/<id>.js e viene
  caricato a richiesta con loadGame(id), solo quando si gioca.

  Per aggiungere un minigioco: crea js/games/<id>.js, aggiungi una voce qui
  e il file alla lista PRECACHE in sw.js.

  Campi:
    id           identificatore (= nome del file)
    title, icon  come appare (icon = emoji di riserva)
    image        icona disegnata (assets/icons/<id>.webp); se manca si usa l'emoji
    description  una riga, per elenchi e conto alla rovescia
    howTo        spiegazione un po' più lunga
    category     UNA categoria principale (vedi CATEGORIES)
    skills       abilità coinvolte (più di una)
    theme        ambientazione / soggetto
    duration     secondi tipici di una manche
    pace         "frenetico" | "veloce" | "tranquillo"
    input        come si comanda: "tocco" | "scorri" | "tieni premuto"
    hands        "una mano" | "due mani"
    difficultyNote  cosa cambia con la difficoltà
    scoring      come si fa punteggio
    added        data di arrivo (per il badge NUOVO)
    tags         parole libere per la ricerca
*/

export const CATEGORIES = [
  { id: "riflessi", label: "Riflessi", icon: "⚡", color: "#ffca3a" },
  { id: "memoria", label: "Memoria", icon: "🧠", color: "#c77dff" },
  { id: "attenzione", label: "Attenzione", icon: "👁️", color: "#36cfc9" },
  { id: "destrezza", label: "Destrezza", icon: "🎮", color: "#8ac926" },
  { id: "calcolo", label: "Calcolo", icon: "🔢", color: "#1982c4" },
  { id: "parole", label: "Parole", icon: "🔤", color: "#f15bb5" },
];

export const PACES = { frenetico: "Frenetico", veloce: "Veloce", tranquillo: "Tranquillo" };

// Un minigioco è "nuovo" per questo numero di giorni dopo l'arrivo.
const NEW_DAYS = 21;

export const CATALOG = [
  {
    id: "semaforo",
    image: "assets/icons/semaforo.webp",
    title: "Semaforo",
    icon: "🚦",
    description: "Tocca appena lo schermo diventa verde. Se tocchi prima, falsa partenza!",
    howTo: "Lo schermo è rosso. In un momento imprevedibile diventa verde: tocca il più in fretta possibile. Chi tocca col rosso fa falsa partenza e finisce ultimo.",
    category: "riflessi",
    skills: ["riflessi", "autocontrollo"],
    theme: "semaforo",
    duration: 6,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = attesa più lunga e imprevedibile.",
    scoring: "Millisecondi di reazione: meno è meglio.",
    added: "2026-09-19",
    tags: ["reazione", "classico", "velocità"],
    load: () => import("./semaforo.js"),
  },
  {
    id: "memory",
    image: "assets/icons/memory.webp",
    title: "Memory",
    icon: "🃏",
    description: "Trova tutte le coppie di forme uguali. Vince chi finisce prima.",
    howTo: "Le carte sono coperte. Girane due: se sono uguali restano scoperte, altrimenti si richiudono. Trova tutte le coppie nel minor tempo.",
    category: "memoria",
    skills: ["memoria visiva", "metodo"],
    theme: "carte e forme",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più coppie (6, 8, 10).",
    scoring: "Tempo per completare: meno è meglio.",
    added: "2026-09-19",
    tags: ["coppie", "carte", "classico", "forme"],
    load: () => import("./memory.js"),
  },
  {
    id: "sequenza",
    image: "assets/icons/sequenza.webp",
    title: "Sequenza",
    icon: "🎵",
    description: "Guarda i tasti che si accendono e ripeti la sequenza. Ogni volta si allunga di uno.",
    howTo: "Quattro tasti colorati si accendono in ordine. Ripeti la sequenza toccandoli. Ogni giro aggiunge un passo: quanto lontano arrivi?",
    category: "memoria",
    skills: ["memoria", "concentrazione"],
    theme: "tasti colorati",
    duration: 50,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = sequenza più lunga e più veloce.",
    scoring: "Passi completati: più è meglio.",
    added: "2026-09-19",
    tags: ["simon", "ritmo", "colori", "classico"],
    load: () => import("./sequenza.js"),
  },
  {
    id: "numeri",
    image: "assets/icons/numeri.webp",
    title: "Numeri",
    icon: "🔢",
    description: "Tocca i numeri in ordine, dall'1 in su, il più in fretta possibile.",
    howTo: "Una griglia di numeri in disordine. Toccali in ordine crescente. Ogni tocco sbagliato costa un secondo.",
    category: "attenzione",
    skills: ["ricerca visiva", "velocità"],
    theme: "numeri",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più numeri (12, 16, 20).",
    scoring: "Tempo per finire, +1 s per errore: meno è meglio.",
    added: "2026-09-19",
    tags: ["ordine", "griglia", "velocità"],
    load: () => import("./numeri.js"),
  },
  {
    id: "bersagli",
    image: "assets/icons/bersagli.webp",
    title: "Bersagli",
    icon: "🎯",
    description: "Tocca i bersagli prima che spariscano. Hai 20 secondi.",
    howTo: "Compaiono cerchi colorati in punti a caso e spariscono in fretta. Colpiscine più che puoi.",
    category: "destrezza",
    skills: ["precisione", "velocità"],
    theme: "bersagli",
    duration: 20,
    pace: "frenetico",
    input: "tocco",
    hands: "due mani",
    difficultyNote: "Più difficile = bersagli più piccoli e più brevi.",
    scoring: "Bersagli colpiti: più è meglio.",
    added: "2026-09-19",
    tags: ["talpa", "colpisci", "velocità"],
    load: () => import("./bersagli.js"),
  },
  {
    id: "calcoli",
    image: "assets/icons/calcoli.webp",
    title: "Calcoli",
    icon: "➕",
    description: "Rispondi a più operazioni che puoi in 25 secondi. Gli errori tolgono un punto.",
    howTo: "Un'operazione e tre risposte. Tocca quella giusta e passa alla prossima. Sbagliare toglie un punto.",
    category: "calcolo",
    skills: ["calcolo mentale", "velocità"],
    theme: "matematica",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = numeri più grandi e moltiplicazioni.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-19",
    tags: ["matematica", "somme", "scuola"],
    load: () => import("./calcoli.js"),
  },
  {
    id: "colori",
    image: "assets/icons/colori.webp",
    title: "Colori",
    icon: "🎨",
    description: "Tocca il colore con cui è SCRITTA la parola, non quello che dice. 20 secondi.",
    howTo: "Appare il nome di un colore scritto con un altro colore. Devi toccare il tasto del colore dell'inchiostro, ignorando la parola. Il cervello prova a fregarti.",
    category: "attenzione",
    skills: ["attenzione", "autocontrollo"],
    theme: "parole e colori",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più inganni e tasti che cambiano posto.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["stroop", "parole", "inganno", "colori"],
    load: () => import("./colori.js"),
  },
  {
    id: "precisione",
    image: "assets/icons/precisione.webp",
    title: "Precisione",
    icon: "🏹",
    description: "Ferma il cursore al centro della zona colorata. Cinque tiri, massimo 100 punti l'uno.",
    howTo: "Un cursore scorre avanti e indietro su una barra. Tocca quando è dentro la zona verde: più vicino al centro, più punti. Cinque tiri.",
    category: "destrezza",
    skills: ["tempismo", "calma"],
    theme: "barra e cursore",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = cursore più veloce e zona più stretta.",
    scoring: "Somma dei cinque tiri (max 500): più è meglio.",
    added: "2026-09-20",
    tags: ["tempismo", "tiro", "barra"],
    load: () => import("./precisione.js"),
  },
  {
    id: "salta",
    image: "assets/icons/salta.webp",
    title: "Salta",
    icon: "🦘",
    description: "Tocca per saltare gli ostacoli. Resisti 30 secondi!",
    howTo: "Il tuo personaggio corre da solo. Tocca per saltare gli ostacoli spinati. La corsa accelera piano piano: quanti ne superi?",
    category: "destrezza",
    skills: ["tempismo", "riflessi"],
    theme: "corsa",
    duration: 30,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più veloce, ostacoli più vicini e più alti.",
    scoring: "Ostacoli superati: più è meglio.",
    added: "2026-09-20",
    tags: ["runner", "corsa", "salto", "azione", "dino"],
    load: () => import("./salta.js"),
  },
  {
    id: "intruso",
    image: "assets/icons/intruso.webp",
    title: "Intruso",
    icon: "🔍",
    description: "Un quadrato ha un colore leggermente diverso dagli altri: toccalo! 20 secondi.",
    howTo: "Una griglia di quadrati tutti uguali… tranne uno, di una sfumatura diversa. Trovalo. A ogni griglia la differenza si riduce.",
    category: "attenzione",
    skills: ["occhio", "percezione dei colori"],
    theme: "colori e griglie",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande e differenze più sottili.",
    scoring: "Intrusi trovati meno errori: più è meglio.",
    added: "2026-09-20",
    tags: ["differenze", "sfumature", "occhio", "griglia"],
    load: () => import("./intruso.js"),
  },
  {
    id: "frecce",
    image: "assets/icons/frecce.webp",
    title: "Frecce",
    icon: "🧭",
    description: "Scorri il dito dove indica la freccia. Se è rossa, vai dalla parte opposta! 20 secondi.",
    howTo: "Appare una freccia: scorri il dito nella sua direzione. Se la freccia è rossa, scorri nella direzione opposta. Veloce!",
    category: "riflessi",
    skills: ["riflessi", "logica"],
    theme: "frecce",
    duration: 20,
    pace: "frenetico",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = più frecce rosse.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["swipe", "direzioni", "inganno", "gesto"],
    load: () => import("./frecce.js"),
  },
  {
    id: "palloncini",
    image: "assets/icons/palloncini.webp",
    title: "Palloncini",
    icon: "🎈",
    description: "Tieni premuto per gonfiare e lascia esattamente alla riga: più sei preciso, più punti.",
    howTo: "Una riga tratteggiata segna quanto gonfiare. Tieni premuto: il palloncino cresce. Lascia quando arriva alla riga: 100 punti se è perfetto, meno man mano che ti allontani. Se lo gonfi troppo oltre la riga, scoppia e vale zero. Cinque palloncini, righe diverse.",
    category: "destrezza",
    skills: ["controllo", "tempismo"],
    theme: "palloncini",
    duration: 30,
    pace: "tranquillo",
    input: "tieni premuto",
    hands: "una mano",
    difficultyNote: "Più difficile = si gonfia più in fretta e scoppia più vicino alla riga.",
    scoring: "Somma dei cinque palloncini (max 500): più vicino alla riga, più punti.",
    added: "2026-09-21",
    tags: ["gonfia", "riga", "controllo", "precisione"],
    load: () => import("./palloncini.js"),
  },
  {
    id: "dipiu",
    image: "assets/icons/dipiu.webp",
    title: "Di più",
    icon: "⚖️",
    description: "Quale riquadro ha più pallini? Tocca in fretta! 20 secondi.",
    howTo: "Due riquadri pieni di pallini. Tocca quello che ne ha di più, a colpo d'occhio. Attenzione: i pallini non hanno tutti la stessa dimensione.",
    category: "attenzione",
    skills: ["stima", "colpo d'occhio"],
    theme: "pallini",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = quantità più vicine tra loro.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-20",
    tags: ["stima", "quantità", "confronto", "occhio"],
    load: () => import("./dipiu.js"),
  },
  {
    id: "tocchi",
    image: "assets/icons/tocchi.webp",
    title: "Tocchi",
    icon: "👆",
    description: "Quanti tocchi riesci a fare in 10 secondi? Tutto lo schermo è il pulsante.",
    howTo: "Dieci secondi, un solo obiettivo: toccare lo schermo più volte che puoi. Con due dita si va più veloci… a te la scelta.",
    category: "riflessi",
    skills: ["velocità", "resistenza"],
    theme: "contatore",
    duration: 10,
    pace: "frenetico",
    input: "tocco",
    hands: "due mani",
    difficultyNote: "La difficoltà non cambia nulla: conta solo la velocità.",
    scoring: "Numero di tocchi: più è meglio.",
    added: "2026-09-21",
    tags: ["tap", "velocità", "sfida", "dita"],
    load: () => import("./tocchi.js"),
  },
  {
    id: "ritmo",
    image: "assets/icons/ritmo.webp",
    title: "Ritmo",
    icon: "🥁",
    description: "Tocca a tempo con il battito: 16 colpi, più sei preciso più punti.",
    howTo: "Senti e vedi un battito regolare. Dopo quattro battiti di preparazione, tocca esattamente sul battito per sedici volte. Ogni colpo vale fino a 100 punti.",
    category: "destrezza",
    skills: ["ritmo", "tempismo"],
    theme: "musica",
    duration: 15,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = battito più veloce (90, 110, 135 BPM).",
    scoring: "Somma della precisione dei 16 colpi (max 1600).",
    added: "2026-09-21",
    tags: ["musica", "battito", "tempo", "metronomo"],
    load: () => import("./ritmo.js"),
  },
  {
    id: "torre",
    image: "assets/icons/torre.webp",
    title: "Torre",
    icon: "🏗️",
    description: "Un blocco scorre: toccalo per farlo cadere sulla torre. La parte che sporge si perde!",
    howTo: "Sopra la torre un blocco va avanti e indietro. Tocca per farlo cadere: quello che non appoggia sul blocco sotto si stacca, e il blocco dopo è più stretto. Fino a 20 blocchi.",
    category: "destrezza",
    skills: ["tempismo", "precisione"],
    theme: "costruzione",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = blocchi più veloci.",
    scoring: "Blocchi impilati (max 20). Allineamento perfetto = nessuna perdita.",
    added: "2026-09-21",
    tags: ["stack", "blocchi", "impilare", "costruire"],
    load: () => import("./torre.js"),
  },
  {
    id: "frenata",
    image: "assets/icons/frenata.webp",
    title: "Frenata",
    icon: "🚗",
    description: "L'auto accelera verso la riga: tocca per frenare e fermati il più vicino possibile.",
    howTo: "L'auto parte da sola e accelera. Tocca una volta per frenare: si fermerà un po' più avanti. Vince chi si ferma più vicino alla riga senza superarla. Cinque tentativi.",
    category: "destrezza",
    skills: ["tempismo", "stima"],
    theme: "auto",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = accelerazioni più forti e frenata più brusca.",
    scoring: "Somma dei cinque tentativi (max 500). Oltre la riga = 0.",
    added: "2026-09-21",
    tags: ["auto", "guida", "freno", "corsa"],
    load: () => import("./frenata.js"),
  },
  {
    id: "cesto",
    image: "assets/icons/cesto.webp",
    title: "Cesto",
    icon: "🧺",
    description: "Trascina il cesto e prendi la frutta che cade. 20 secondi.",
    howTo: "La frutta cade dall'alto in punti diversi. Tieni il dito sullo schermo e trascina il cesto sotto ogni frutto. Ogni frutto preso vale un punto.",
    category: "destrezza",
    skills: ["coordinazione", "velocità"],
    theme: "frutta",
    duration: 20,
    pace: "veloce",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = frutta più veloce e più fitta.",
    scoring: "Frutti presi su quelli caduti: più è meglio.",
    added: "2026-09-21",
    tags: ["cattura", "frutta", "trascina", "cadere"],
    load: () => import("./cesto.js"),
  },
  {
    id: "lampi",
    image: "assets/icons/lampi.webp",
    title: "Lampi",
    icon: "💡",
    description: "Alcuni lampi appaiono in un attimo: quanti erano? Otto giri.",
    howTo: "Sullo schermo lampeggiano dei punti luminosi, uno dopo l'altro, in fretta. Alla fine rispondi col tastierino: quanti erano? Otto giri, sempre più rapidi.",
    category: "attenzione",
    skills: ["attenzione", "conteggio"],
    theme: "luci",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più lampi e più veloci.",
    scoring: "Risposte giuste su 8.",
    added: "2026-09-21",
    tags: ["contare", "lampi", "luci", "occhio"],
    load: () => import("./lampi.js"),
  },
  {
    id: "meta",
    image: "assets/icons/meta.webp",
    title: "Metà",
    icon: "📏",
    description: "Tocca il punto esatto a metà della barra. Cinque barre.",
    howTo: "Appare una barra colorata. Tocca dove pensi sia il suo centro esatto. Più sei vicino, più punti. A difficile le barre sono anche inclinate.",
    category: "attenzione",
    skills: ["stima", "colpo d'occhio"],
    theme: "geometria",
    duration: 20,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = barre inclinate.",
    scoring: "Somma della precisione delle cinque barre (max 500).",
    added: "2026-09-21",
    tags: ["centro", "stima", "misura", "occhio"],
    load: () => import("./meta.js"),
  },
  {
    id: "cinquesecondi",
    image: "assets/icons/cinquesecondi.webp",
    title: "Cronometro cieco",
    icon: "⏱️",
    description: "Il cronometro sparisce dopo un secondo: fermalo a 5,00 s a occhi chiusi.",
    howTo: "Tocca per avviare il cronometro. Dopo un secondo i numeri spariscono. Tocca di nuovo quando pensi che sia passato esattamente il tempo richiesto. Tre tentativi.",
    category: "attenzione",
    skills: ["senso del tempo", "calma"],
    theme: "tempo",
    duration: 25,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: 5 s sempre, visibile 2 s. Difficile: bersagli diversi (3-8 s).",
    scoring: "Somma della precisione dei tre tentativi (max 300).",
    added: "2026-09-21",
    tags: ["tempo", "cronometro", "secondi", "stima"],
    load: () => import("./cinquesecondi.js"),
  },
  {
    id: "copia",
    image: "assets/icons/copia.webp",
    title: "Copia",
    icon: "🪞",
    description: "Guarda lo schema di caselle accese, poi ricopialo. Sei schemi sempre più grandi.",
    howTo: "Una griglia mostra alcune caselle accese per un attimo, poi si spegne. Tocca le caselle per ricomporre lo stesso schema e conferma. Ogni schema ha una casella in più.",
    category: "memoria",
    skills: ["memoria visiva", "attenzione"],
    theme: "griglie",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande, schemi più fitti, meno tempo per guardare.",
    scoring: "Schemi esatti su 6.",
    added: "2026-09-21",
    tags: ["schema", "memoria", "griglia", "copiare"],
    load: () => import("./copia.js"),
  },
  {
    id: "anagrammi",
    image: "assets/icons/anagrammi.webp",
    title: "Anagrammi",
    icon: "🔤",
    description: "Le lettere sono in disordine: tocca nell'ordine giusto per ricomporre la parola. 30 secondi.",
    howTo: "Vedi le lettere di una parola mescolate. Toccale nell'ordine giusto: se la parola è corretta passi alla prossima, altrimenti le lettere tornano a posto. Puoi saltare una parola.",
    category: "parole",
    skills: ["vocabolario", "logica"],
    theme: "parole",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = parole più lunghe.",
    scoring: "Parole ricomposte: più è meglio.",
    added: "2026-09-21",
    tags: ["lettere", "parole", "anagramma", "italiano"],
    load: () => import("./anagrammi.js"),
  },
  {
    id: "dieci",
    image: "assets/icons/dieci.webp",
    title: "Dieci",
    icon: "🔟",
    description: "Tocca due numeri che sommati fanno 10. Spariscono e ne arrivano altri. 25 secondi.",
    howTo: "Una griglia di numeri. Tocca due numeri la cui somma è 10: spariscono e vengono sostituiti. C'è sempre almeno una coppia possibile. Più coppie trovi, meglio è.",
    category: "calcolo",
    skills: ["calcolo", "ricerca visiva"],
    theme: "numeri",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande.",
    scoring: "Coppie trovate: più è meglio.",
    added: "2026-09-21",
    tags: ["somma", "coppie", "matematica", "dieci"],
    load: () => import("./dieci.js"),
  },
  {
    id: "labirinto",
    image: "assets/icons/labirinto.webp",
    title: "Labirinto",
    icon: "🌀",
    description: "Trascina il dito dall'ingresso all'uscita senza toccare i muri.",
    howTo: "Appoggia il dito sulla casella verde e scorri fino alla stella dorata restando nei corridoi. Se tocchi un muro torni all'ingresso e perdi un secondo. Vince chi esce prima.",
    category: "destrezza",
    skills: ["precisione", "orientamento"],
    theme: "labirinto",
    duration: 40,
    pace: "tranquillo",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = labirinto più grande e corridoi più stretti.",
    scoring: "Tempo per uscire, +1 s per ogni tocco al muro: meno è meglio.",
    added: "2026-09-21",
    tags: ["labirinto", "dito", "percorso", "muri"],
    load: () => import("./labirinto.js"),
  },
  {
    id: "melodia",
    image: "assets/icons/melodia.webp",
    title: "Melodia",
    icon: "🎹",
    description: "Ascolta una melodia sui quattro tasti e ripetila. Ogni giro è nuova e più lunga.",
    howTo: "Quattro tasti come un pianoforte. Una melodia suona una volta sola (i tasti si accendono): ripetila toccando i tasti nello stesso ordine. Ogni giro la melodia cambia e si allunga. Se sbagli, si passa alla successiva.",
    category: "memoria",
    skills: ["memoria uditiva", "attenzione"],
    theme: "pianoforte",
    duration: 50,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = melodie più veloci.",
    scoring: "Note giuste (max 52).",
    added: "2026-09-21",
    tags: ["musica", "note", "memoria", "piano"],
    load: () => import("./melodia.js"),
  },
  {
    id: "ordina",
    image: "assets/icons/ordina.webp",
    title: "Ordina",
    icon: "🫧",
    description: "Tocca i cerchi dal più piccolo al più grande, serie dopo serie.",
    howTo: "Compaiono cerchi di grandezze diverse: toccali in ordine, dal più piccolo al più grande. Finita una serie ne arriva un'altra. Un errore fa perdere tempo, non punti.",
    category: "attenzione",
    skills: ["colpo d'occhio", "velocità"],
    theme: "bolle",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più cerchi per serie (5, 7, 9) e grandezze più vicine.",
    scoring: "Tocchi giusti in 25 s: più è meglio.",
    added: "2026-09-21",
    tags: ["grandezza", "ordine", "cerchi", "occhio"],
    load: () => import("./ordina.js"),
  },
  {
    id: "parola",
    image: "assets/icons/parola.webp",
    title: "Parola nascosta",
    icon: "🔠",
    description: "Trova la parola nascosta nella griglia di lettere e tocca le sue lettere in ordine.",
    howTo: "In alto c'è la parola da trovare; nella griglia è scritta in orizzontale o in verticale. Tocca la sua prima lettera, poi le altre in ordine. Una lettera sbagliata azzera la selezione. 40 secondi, più parole possibili.",
    category: "parole",
    skills: ["lettura", "colpo d'occhio"],
    theme: "griglia di lettere",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglia più grande (5×5, 6×6, 7×7).",
    scoring: "Parole trovate: più è meglio.",
    added: "2026-09-21",
    tags: ["parole", "lettere", "cerca", "griglia"],
    load: () => import("./parola.js"),
  },
  {
    id: "tris",
    image: "assets/icons/tris.webp",
    title: "Tris veloce",
    icon: "❌",
    description: "Partite lampo di tris contro il telefono: vinci 3 punti, pareggi 1.",
    howTo: "Sei la X e cominci tu. Vinci mettendo tre X in fila; il telefono risponde subito. Finita una partita ne parte un'altra, per 30 secondi. Vittoria 3 punti, pareggio 1, sconfitta 0.",
    category: "attenzione",
    skills: ["logica", "rapidità"],
    theme: "tris",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = avversario che si distrae di rado.",
    scoring: "Punti (3 per vittoria, 1 per pareggio): più è meglio.",
    added: "2026-09-21",
    tags: ["tris", "logica", "partite", "x e o"],
    load: () => import("./tris.js"),
  },
  {
    id: "pesca",
    image: "assets/icons/pesca.webp",
    title: "Pesca",
    icon: "🎣",
    description: "Quando il galleggiante affonda, tocca subito: cinque pesci, più sei rapido più punti.",
    howTo: "Il galleggiante ondeggia. In un momento imprevedibile un pesce abbocca e il galleggiante affonda di colpo: tocca il più in fretta possibile. Se tocchi prima, il pesce scappa. Attento ai finti morsi nei livelli più difficili.",
    category: "riflessi",
    skills: ["riflessi", "pazienza"],
    theme: "lago",
    duration: 35,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = meno tempo per rispondere e finti morsi.",
    scoring: "Somma dei cinque pesci (max 500): più è meglio.",
    added: "2026-09-21",
    tags: ["pesce", "attesa", "reazione", "acqua"],
    load: () => import("./pesca.js"),
  },
  {
    id: "traiettoria",
    image: "assets/icons/traiettoria.webp",
    title: "Traiettoria",
    icon: "🎯",
    description: "Scorri dalla palla verso il bersaglio in movimento: otto lanci, centra più che puoi.",
    howTo: "Il bersaglio si muove in alto. Scorri il dito dalla palla nella direzione in cui vuoi lanciarla: la palla parte dritta. Centro pieno 100 punti, anelli esterni meno. Otto lanci.",
    category: "destrezza",
    skills: ["mira", "tempismo"],
    theme: "tiro al bersaglio",
    duration: 35,
    pace: "veloce",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = bersaglio più veloce.",
    scoring: "Somma degli otto lanci (max 800): più è meglio.",
    added: "2026-09-21",
    tags: ["bersaglio", "lancio", "mira", "palla"],
    load: () => import("./traiettoria.js"),
  },
  {
    id: "capitali",
    image: "assets/icons/capitali.webp",
    title: "Capitali",
    icon: "🌍",
    description: "Qual è la capitale di…? Quattro risposte, 25 secondi a raffica.",
    howTo: "Compare un paese con la sua bandiera: tocca la capitale giusta tra le quattro. Ogni risposta giusta vale +1, ogni errore −1. Più rispondi, più punti.",
    category: "memoria",
    skills: ["cultura", "rapidità"],
    theme: "geografia",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: solo capitali famosissime. Difficile: anche quelle meno note.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["geografia", "quiz", "bandiere", "mondo"],
    load: () => import("./capitali.js"),
  },
  {
    id: "talpe",
    image: "assets/icons/talpe.webp",
    title: "Talpe",
    icon: "🐹",
    description: "Le talpe spuntano dalle buche per un attimo: toccale! Le bombe invece no.",
    howTo: "Nove buche. Le talpe fanno capolino e spariscono in fretta: toccale per prendere un punto. Ogni tanto spunta una bomba: toccarla toglie un punto. 20 secondi.",
    category: "riflessi",
    skills: ["riflessi","attenzione"],
    theme: "buche e talpe",
    duration: 20,
    pace: "frenetico",
    input: "tocco",
    hands: "due mani",
    difficultyNote: "Più difficile = talpe più rapide e più bombe.",
    scoring: "Talpe colpite meno bombe: più è meglio.",
    added: "2026-09-21",
    tags: ["talpe","buche","bombe","riflessi"],
    load: () => import("./talpe.js"),
  },
  {
    id: "lampadine",
    image: "assets/icons/lampadine.webp",
    title: "Lampadine",
    icon: "💡",
    description: "Le lampadine si accendono una alla volta, sempre più in fretta: spegnile al volo.",
    howTo: "Sei lampadine. Una si accende: toccala per spegnerla prima che si spenga da sola. Man mano il tempo per reagire si accorcia. Toccare una lampadina spenta toglie un punto.",
    category: "riflessi",
    skills: ["riflessi","prontezza"],
    theme: "lampadine",
    duration: 20,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = tempo per reagire più corto.",
    scoring: "Lampadine spente meno tocchi sbagliati: più è meglio.",
    added: "2026-09-21",
    tags: ["luci","reazione","spegni"],
    load: () => import("./lampadine.js"),
  },
  {
    id: "sfuggente",
    image: "assets/icons/sfuggente.webp",
    title: "Sfuggente",
    icon: "🏓",
    description: "Una pallina rimbalza per lo schermo: toccala! Ogni presa la rende più veloce e più piccola.",
    howTo: "La pallina rimbalza sui bordi. Toccala per prenderla: ogni volta riparte più veloce e un po' più piccola. 20 secondi, più prese possibili.",
    category: "riflessi",
    skills: ["riflessi","mira"],
    theme: "pallina che rimbalza",
    duration: 20,
    pace: "frenetico",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = pallina più veloce e più piccola fin dall'inizio.",
    scoring: "Prese: più è meglio.",
    added: "2026-09-21",
    tags: ["pallina","rimbalzo","velocità"],
    load: () => import("./sfuggente.js"),
  },
  {
    id: "suoni",
    image: "assets/icons/suoni.webp",
    title: "Suoni",
    icon: "🔔",
    description: "Un memory per le orecchie: le tessere sono tutte uguali, ognuna nasconde una nota.",
    howTo: "Tocca una tessera: suona una nota. Toccane un'altra: se la nota è la stessa, la coppia resta aperta; altrimenti si richiudono. Trova tutte le coppie ascoltando.",
    category: "memoria",
    skills: ["memoria uditiva","orecchio"],
    theme: "note nascoste",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più coppie (4, 6, 8).",
    scoring: "Coppie trovate: più è meglio.",
    added: "2026-09-21",
    tags: ["memory","note","orecchio","suoni"],
    load: () => import("./suoni.js"),
  },
  {
    id: "cosamanca",
    image: "assets/icons/cosamanca.webp",
    title: "Cosa manca",
    icon: "🔎",
    description: "Guarda le forme, poi una sparisce e le altre si mescolano: quale manca?",
    howTo: "Un gruppo di forme resta a schermo qualche secondo. Poi una sparisce e le altre cambiano posto: scegli tra le quattro proposte quella che manca. Otto giri.",
    category: "memoria",
    skills: ["memoria visiva","attenzione"],
    theme: "forme",
    duration: 50,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più forme e meno tempo per guardare.",
    scoring: "Risposte giuste su 8.",
    added: "2026-09-21",
    tags: ["memoria","forme","manca","osserva"],
    load: () => import("./cosamanca.js"),
  },
  {
    id: "cifre",
    image: "assets/icons/cifre.webp",
    title: "Cifre",
    icon: "🔢",
    description: "Un numero compare e sparisce: riscrivilo. Ogni volta ha una cifra in più.",
    howTo: "Il numero resta a schermo qualche secondo, poi sparisce: riscrivilo sul tastierino. Se è giusto, il prossimo ha una cifra in più. Al primo errore si ferma. Punteggio: tutte le cifre ricordate.",
    category: "memoria",
    skills: ["memoria","concentrazione"],
    theme: "numeri",
    duration: 60,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = si parte con più cifre e restano a schermo meno tempo.",
    scoring: "Cifre ricordate: più è meglio.",
    added: "2026-09-21",
    tags: ["numeri","memoria","cifre","tastierino"],
    load: () => import("./cifre.js"),
  },
  {
    id: "quanti",
    image: "assets/icons/quanti.webp",
    title: "Quanti",
    icon: "🔺",
    description: "Tante forme sparse: quanti sono i triangoli? Conta e rispondi.",
    howTo: "Compaiono cerchi, quadrati e triangoli mescolati. La domanda dice cosa contare: tocca il numero giusto sul tastierino. Sei giri.",
    category: "attenzione",
    skills: ["colpo d'occhio","conteggio"],
    theme: "forme sparse",
    duration: 40,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più forme a schermo.",
    scoring: "Conteggi giusti su 6.",
    added: "2026-09-21",
    tags: ["conta","forme","occhio"],
    load: () => import("./quanti.js"),
  },
  {
    id: "gemelli",
    image: "assets/icons/gemelli.webp",
    title: "Gemelli",
    icon: "🪞",
    description: "Due griglie colorate: sono identiche o c'è una casella diversa? Decidi al volo.",
    howTo: "Due griglie una accanto all'altra. Se sono identiche tocca \"Uguali\", se c'è anche una sola casella diversa tocca \"Diverse\". +1 giusta, −1 sbagliata. 20 secondi.",
    category: "attenzione",
    skills: ["colpo d'occhio","confronto"],
    theme: "griglie colorate",
    duration: 20,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = griglie più grandi (3×3, 4×4, 5×5).",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["confronto","differenze","griglia"],
    load: () => import("./gemelli.js"),
  },
  {
    id: "bussolotti",
    image: "assets/icons/bussolotti.webp",
    title: "Bussolotti",
    icon: "🥤",
    description: "La pallina va sotto un bicchiere, i bicchieri si mescolano: seguila con gli occhi.",
    howTo: "Guarda sotto quale bicchiere finisce la pallina. I bicchieri si scambiano di posto, sempre più in fretta. Alla fine tocca quello giusto. Sei giri.",
    category: "attenzione",
    skills: ["attenzione","inseguimento"],
    theme: "gioco dei bicchieri",
    duration: 45,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più scambi, più rapidi, e quattro bicchieri.",
    scoring: "Palline trovate su 6.",
    added: "2026-09-21",
    tags: ["bicchieri","attenzione","segui"],
    load: () => import("./bussolotti.js"),
  },
  {
    id: "equilibrio",
    image: "assets/icons/equilibrio.webp",
    title: "Equilibrio",
    icon: "⚖️",
    description: "Tieni la pallina in equilibrio sull'asse inclinandola col tocco. Resisti 30 secondi.",
    howTo: "La pallina è su un'asse in bilico e ogni tanto una raffica la spinge. Tocca a sinistra o a destra per inclinare l'asse e riportarla al centro. Se cade, finisce.",
    category: "destrezza",
    skills: ["controllo","prontezza"],
    theme: "asse in bilico",
    duration: 30,
    pace: "veloce",
    input: "tieni premuto",
    hands: "una mano",
    difficultyNote: "Più difficile = pallina più scivolosa e raffiche più forti.",
    scoring: "Secondi in equilibrio (max 30).",
    added: "2026-09-21",
    tags: ["equilibrio","asse","controllo"],
    load: () => import("./equilibrio.js"),
  },
  {
    id: "serpente",
    image: "assets/icons/serpente.webp",
    title: "Serpente",
    icon: "🐍",
    description: "Il classico serpente: scorri per girare, mangia i frutti, non sbattere.",
    howTo: "Il serpente avanza da solo; scorri il dito nella direzione in cui vuoi girare. Ogni frutto lo allunga. Contro i bordi o contro se stesso, finisce. 30 secondi.",
    category: "destrezza",
    skills: ["destrezza","pianificazione"],
    theme: "serpente",
    duration: 30,
    pace: "veloce",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = serpente più veloce.",
    scoring: "Frutti mangiati: più è meglio.",
    added: "2026-09-21",
    tags: ["serpente","classico","frutti"],
    load: () => import("./serpente.js"),
  },
  {
    id: "strada",
    image: "assets/icons/strada.webp",
    title: "Strada",
    icon: "🚙",
    description: "La strada curva: tieni la macchina sull'asfalto toccando a sinistra o a destra.",
    howTo: "La macchina corre e la strada curva. Tocca a sinistra o a destra per sterzare. Se esci dall'asfalto la corsa finisce. Punteggio: metri percorsi in 30 secondi.",
    category: "destrezza",
    skills: ["controllo","riflessi"],
    theme: "strada che curva",
    duration: 30,
    pace: "veloce",
    input: "tieni premuto",
    hands: "una mano",
    difficultyNote: "Più difficile = strada più stretta e curve più strette.",
    scoring: "Metri percorsi (max 300).",
    added: "2026-09-21",
    tags: ["auto","strada","curve","sterzo"],
    load: () => import("./strada.js"),
  },
  {
    id: "bilancia",
    image: "assets/icons/bilancia.webp",
    title: "Bilancia",
    icon: "🧮",
    description: "Due conti sui piatti: quale pesa di più? O sono uguali?",
    howTo: "A sinistra e a destra un conto ciascuno. Tocca il piatto che vale di più, oppure \"Uguali\". +1 giusta, −1 sbagliata. 25 secondi.",
    category: "calcolo",
    skills: ["calcolo","confronto"],
    theme: "bilancia",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = numeri più grandi e moltiplicazioni.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["conti","confronto","maggiore"],
    load: () => import("./bilancia.js"),
  },
  {
    id: "prossimo",
    image: "assets/icons/prossimo.webp",
    title: "Prossimo",
    icon: "➡️",
    description: "Una sequenza di numeri segue una regola: qual è il prossimo?",
    howTo: "Quattro numeri seguono una regola (salti uguali, raddoppi, salti alternati…). Scegli tra le tre risposte quella che continua la sequenza. +1 giusta, −1 sbagliata.",
    category: "calcolo",
    skills: ["logica","calcolo"],
    theme: "sequenze di numeri",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = regole più varie (anche quadrati e salti crescenti).",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["sequenze","regola","logica"],
    load: () => import("./prossimo.js"),
  },
  {
    id: "orologio",
    image: "assets/icons/orologio.webp",
    title: "Orologio",
    icon: "🕒",
    description: "Che ora segna l'orologio a lancette? Scegli tra le quattro in cifre.",
    howTo: "Un orologio a lancette segna un'ora: tocca tra le quattro proposte quella giusta in cifre. Occhio alle lancette scambiate. +1 giusta, −1 sbagliata.",
    category: "calcolo",
    skills: ["lettura dell'ora","rapidità"],
    theme: "orologio a lancette",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: ore e mezz'ore. Normale: quarti. Difficile: cinque minuti.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["ora","lancette","orologio"],
    load: () => import("./orologio.js"),
  },
  {
    id: "ortografia",
    image: "assets/icons/ortografia.webp",
    title: "Ortografia",
    icon: "✏️",
    description: "Quattro modi di scrivere la stessa parola: uno solo è giusto.",
    howTo: "La stessa parola scritta in quattro modi, con doppie, lettere scambiate o mancanti. Tocca quella scritta bene. +1 giusta, −1 sbagliata. 25 secondi.",
    category: "parole",
    skills: ["ortografia","lettura"],
    theme: "parole scritte",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = parole più lunghe e insidiose.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["parole","doppie","scrivere"],
    load: () => import("./ortografia.js"),
  },
  {
    id: "rime",
    image: "assets/icons/rime.webp",
    title: "Rime",
    icon: "🎤",
    description: "Quale delle quattro parole fa rima con quella in alto?",
    howTo: "In alto una parola; sotto quattro parole, una sola fa rima con lei. Toccala. +1 giusta, −1 sbagliata. 25 secondi.",
    category: "parole",
    skills: ["parole","orecchio"],
    theme: "rime",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = le parole sbagliate finiscono con la stessa lettera.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["rime","poesia","parole"],
    load: () => import("./rime.js"),
  },
  {
    id: "contrari",
    image: "assets/icons/contrari.webp",
    title: "Contrari",
    icon: "↔️",
    description: "Caldo… freddo! Tocca il contrario della parola in alto.",
    howTo: "In alto una parola; sotto quattro parole, una sola è il suo contrario. Toccala. +1 giusta, −1 sbagliata. 25 secondi.",
    category: "parole",
    skills: ["parole","rapidità"],
    theme: "contrari",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "La difficoltà non cambia le parole: conta la rapidità.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-21",
    tags: ["contrari","opposti","parole"],
    load: () => import("./contrari.js"),
  },
  {
    id: "specchio",
    image: "assets/icons/specchio.webp",
    title: "Specchio",
    icon: "🪞",
    description: "Ricopia il disegno allo specchio: le caselle accese, ribaltate.",
    howTo: "A sinistra alcune caselle sono accese. A destra tocca le caselle che formano lo stesso disegno ribaltato, come in uno specchio. Quando è uguale, arriva il prossimo. 30 secondi.",
    category: "attenzione",
    skills: ["attenzione","orientamento"],
    theme: "specchio",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = più caselle accese per disegno.",
    scoring: "Disegni completati su 12: più è meglio.",
    added: "2026-09-22",
    tags: ["specchio","simmetria","griglia"],
    load: () => import("./specchio.js"),
  },
  {
    id: "maggiore",
    image: "assets/icons/maggiore.webp",
    title: "Maggiore",
    icon: "🆚",
    description: "Due conti, uno a sinistra e uno a destra: tocca quello che vale di più.",
    howTo: "Sullo schermo due numeri o due conti (somme, sottrazioni, moltiplicazioni…). Tocca quello che vale di più. +1 giusta, −1 sbagliata. 25 secondi.",
    category: "calcolo",
    skills: ["calcolo","rapidità"],
    theme: "confronto",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: numeri e somme lontani tra loro. Difficile: moltiplicazioni e divisioni con risultati vicini.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-22",
    tags: ["confronto","numeri","maggiore","minore"],
    load: () => import("./maggiore.js"),
  },
  {
    id: "sillabe",
    image: "assets/icons/sillabe.webp",
    title: "Sillabe",
    icon: "🔡",
    description: "Le sillabe di una parola in disordine: toccale nell'ordine giusto.",
    howTo: "Una parola è stata divisa in sillabe e mescolata. Tocca le sillabe nell'ordine giusto per ricomporla; una sillaba sbagliata trema e non conta. In difficile c'è anche una sillaba intrusa. 30 secondi.",
    category: "parole",
    skills: ["parole","ortografia"],
    theme: "sillabe",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: parole corte. Difficile: parole lunghe e una sillaba intrusa.",
    scoring: "Parole ricomposte: più è meglio.",
    added: "2026-09-22",
    tags: ["sillabe","parole","ordine"],
    load: () => import("./sillabe.js"),
  },
  {
    id: "manopola",
    image: "assets/icons/manopola.webp",
    title: "Manopola",
    icon: "🎛️",
    description: "Ruota la manopola e lascia la lancetta esattamente sulla tacca.",
    howTo: "Una manopola con una lancetta e, sul bordo, una tacca gialla. Trascina il dito intorno alla manopola per ruotare la lancetta e sollevalo quando è sulla tacca. Più sei vicino, più punti (fino a 100). 6 tentativi.",
    category: "destrezza",
    skills: ["controllo","precisione"],
    theme: "manopola",
    duration: 30,
    pace: "tranquillo",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = tolleranza più stretta per i 100 punti.",
    scoring: "Somma dei punti su 600: più è meglio.",
    added: "2026-09-22",
    tags: ["manopola","ruota","precisione","angolo"],
    load: () => import("./manopola.js"),
  },
  {
    id: "alvolo",
    image: "assets/icons/alvolo.webp",
    title: "Al volo",
    icon: "🟢",
    description: "Il cursore corre sulla barra: tocca quando è nella zona verde.",
    howTo: "Un cursore va avanti e indietro su una barra. Tocca quando è dentro la zona verde: al centro vale 100, ai bordi meno, fuori zero. Ogni tentativo la zona si restringe e il cursore accelera. 8 tentativi.",
    category: "riflessi",
    skills: ["riflessi","tempismo"],
    theme: "barra",
    duration: 30,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = cursore più veloce.",
    scoring: "Somma dei punti su 800: più è meglio.",
    added: "2026-09-22",
    tags: ["tempismo","barra","cursore","zona"],
    load: () => import("./alvolo.js"),
  },
  {
    id: "percorso",
    image: "assets/icons/percorso.webp",
    title: "Percorso",
    icon: "🛤️",
    description: "Guarda il percorso che si accende sulla griglia, poi rifallo.",
    howTo: "Sulla griglia si accende un percorso, una casella dopo l'altra, dalla casella segnata. Poi tocca le caselle nello stesso ordine. Ogni percorso giusto, il prossimo è più lungo di una casella; sbagliando lo rivedi, ma al terzo errore finisce.",
    category: "memoria",
    skills: ["memoria","orientamento"],
    theme: "griglia",
    duration: 45,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = si parte da percorsi più lunghi.",
    scoring: "Percorsi completati: più è meglio.",
    added: "2026-09-22",
    tags: ["percorso","memoria","griglia","sequenza"],
    load: () => import("./percorso.js"),
  },
  {
    id: "resto",
    image: "assets/icons/resto.webp",
    title: "Resto",
    icon: "💶",
    description: "Costa tanto, paghi con una banconota: quanto è il resto?",
    howTo: "Un prezzo e la banconota con cui paghi. Tocca il resto giusto tra i quattro proposti. +1 giusta, −1 sbagliata. 25 secondi.",
    category: "calcolo",
    skills: ["calcolo","soldi"],
    theme: "negozio",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: prezzi interi con 10 e 20 €. Difficile: centesimi e banconote da 100 €.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-22",
    tags: ["resto","soldi","euro","spesa"],
    load: () => import("./resto.js"),
  },
  {
    id: "lettere",
    image: "assets/icons/lettere.webp",
    title: "Lettere",
    icon: "🔍",
    description: "Quante volte compare la lettera nella frase? Conta e rispondi.",
    howTo: "Una frase e una lettera in grande. Conta quante volte la lettera compare nella frase (maiuscole e minuscole contano uguale) e tocca il numero. 8 frasi, 40 secondi in tutto.",
    category: "attenzione",
    skills: ["attenzione","lettura"],
    theme: "frasi",
    duration: 40,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Facile: solo vocali. Difficile: anche lettere rare.",
    scoring: "Frasi giuste su 8: più è meglio.",
    added: "2026-09-22",
    tags: ["lettere","contare","frase","attenzione"],
    load: () => import("./lettere.js"),
  },
  {
    id: "cerchi",
    image: "assets/icons/cerchi.webp",
    title: "Cerchi",
    icon: "⭕",
    description: "Un cerchio si restringe: tocca quando combacia con l'anello.",
    howTo: "Un anello giallo e un cerchio azzurro che si restringe verso il centro. Tocca nell'istante in cui il cerchio è grande quanto l'anello: fino a 100 punti a giro. Otto giri, sempre più veloci.",
    category: "riflessi",
    skills: ["riflessi","tempismo"],
    theme: "cerchi",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = il cerchio scende più in fretta.",
    scoring: "Somma dei punti su 800: più è meglio.",
    added: "2026-09-22",
    tags: ["tempismo","cerchio","anello","ritmo"],
    load: () => import("./cerchi.js"),
  },
  {
    id: "rimbalzo",
    image: "assets/icons/rimbalzo.webp",
    title: "Rimbalzo",
    icon: "🏓",
    description: "Muovi la racchetta e tieni la pallina in gioco: ogni rimbalzo un punto.",
    howTo: "Una racchetta in basso e una pallina che rimbalza sulle pareti. Trascina il dito per muovere la racchetta e colpisci la pallina: ogni rimbalzo vale un punto e la pallina accelera. Tre palline, 30 secondi.",
    category: "destrezza",
    skills: ["controllo","riflessi"],
    theme: "racchetta",
    duration: 30,
    pace: "frenetico",
    input: "scorri",
    hands: "una mano",
    difficultyNote: "Più difficile = racchetta più corta e pallina più veloce.",
    scoring: "Rimbalzi sulla racchetta: più è meglio.",
    added: "2026-09-22",
    tags: ["racchetta","pallina","rimbalzo","ping pong"],
    load: () => import("./rimbalzo.js"),
  },
  {
    id: "abbinamenti",
    image: "assets/icons/abbinamenti.webp",
    title: "Abbinamenti",
    icon: "🎨",
    description: "Quattro oggetti su quattro colori: ricorda chi stava su cosa.",
    howTo: "Quattro oggetti, ognuno su una card colorata, restano a schermo qualche secondo. Poi: “di che colore era la mela?”. Tre giri da tre domande, 5 secondi per rispondere.",
    category: "memoria",
    skills: ["memoria","associazione"],
    theme: "colori",
    duration: 60,
    pace: "tranquillo",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "Più difficile = le card restano a schermo meno tempo.",
    scoring: "Colori giusti su 9: più è meglio.",
    added: "2026-09-22",
    tags: ["memoria","colori","oggetti","abbinare"],
    load: () => import("./abbinamenti.js"),
  },
  {
    id: "plurali",
    image: "assets/icons/plurali.webp",
    title: "Plurali",
    icon: "🐑",
    description: "Uovo… uova! Tocca il plurale giusto della parola in alto.",
    howTo: "In alto una parola al singolare; sotto quattro plurali, uno solo è giusto (occhio a quelli irregolari: uova, braccia, dita…). +1 giusta, −1 sbagliata. 25 secondi.",
    category: "parole",
    skills: ["parole","grammatica"],
    theme: "plurali",
    duration: 25,
    pace: "veloce",
    input: "tocco",
    hands: "una mano",
    difficultyNote: "La difficoltà non cambia le parole: conta la rapidità.",
    scoring: "Giuste meno sbagliate: più è meglio.",
    added: "2026-09-22",
    tags: ["plurali","grammatica","parole","italiano"],
    load: () => import("./plurali.js"),
  },
];

export const ALL_GAME_IDS = CATALOG.map((g) => g.id);

export function getEntry(id) {
  return CATALOG.find((g) => g.id === id);
}

export function getCategory(id) {
  return CATEGORIES.find((c) => c.id === id);
}

export function isNew(entry, now = Date.now()) {
  const added = Date.parse(entry.added);
  return Number.isFinite(added) && now - added < NEW_DAYS * 86400000;
}

// Ricerca testuale su tutti i campi descrittivi.
export function matches(entry, query) {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const hay = [
    entry.title, entry.description, entry.howTo, entry.theme, entry.category,
    entry.pace, entry.input, ...entry.skills, ...entry.tags,
    getCategory(entry.category)?.label,
  ].join(" ").toLowerCase();
  return q.split(/\s+/).every((word) => hay.includes(word));
}

// ---------------------------------------------------------------
// Caricamento a richiesta del codice di un minigioco
// ---------------------------------------------------------------

const loaded = new Map();   // id -> Promise del gioco completo
const resolved = new Map(); // id -> gioco completo, quando il caricamento è finito

// Ritorna il gioco completo: scheda del catalogo + codice del modulo.
export async function loadGame(id) {
  if (loaded.has(id)) return loaded.get(id);
  const entry = getEntry(id);
  if (!entry) throw new Error(`Minigioco sconosciuto: ${id}`);
  const promise = entry.load().then((mod) => {
    const game = { ...entry, ...mod.default };
    resolved.set(id, game);
    return game;
  });
  loaded.set(id, promise);
  return promise;
}

// Il gioco completo se è già stato caricato, altrimenti null (senza attese).
export function getLoaded(id) {
  return resolved.get(id) || null;
}

export function preloadGames(ids) {
  return Promise.allSettled(ids.map((id) => loadGame(id)));
}
